"""Generate the theme from tokens.json (technical specification §8.10, visual system): one source, two outputs.

    uv run python scripts/theme/gen_theme.py [--check | --dump]

Writes
    src/roundtable_souls/ui/qml/Theme/Theme.qml   the QML singleton (module Theme), with its qmldir
    src/roundtable_souls/ui/theme_tokens.py       the same roles as plain Python data, which ui/theme.py reads

Hand edits to either output are a bug: edit tokens.json and rerun. `--check` writes nothing and exits 1 when an
output is not current (a CI gate). `--dump` prints every colour role per theme with its OKLCH.

tokens.json follows the W3C design-tokens shape ({"$type", "$value"} leaves inside groups). Colour values may be
    "#RRGGBB" / "#RRGGBBAA"                             an sRGB hex
    {"colorSpace": "oklch", "components": [L, C, H]}   an OKLCH colour (L 0..1, C, H in degrees), gamut-mapped
    "{path.to.other.token}"                            a reference
and any colour token may carry "$extensions": {"roundtable": {"alpha": 0.7, "dL": 0.06, "composite": "{ref}"}}:
    alpha      the alpha the role is used at (15% status backgrounds, 70% secondary text ...)
    dL         an OKLCH lightness offset applied to the referenced colour (hover +0.06, press -0.10)
    composite  flatten the (translucent) value over this opaque colour and emit an opaque colour
The colour maths is in colour.py, shared with the contrast test (tests/unit/test_theme_contrast.py).
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from colour import Rgba, composite, oklch_to_srgb, parse_hex, qt_hex, shift_lightness, srgb_to_oklch  # noqa: E402

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
TOKENS = HERE / "tokens.json"
UI = ROOT / "src" / "roundtable_souls" / "ui"
OUT_QML = UI / "qml" / "Theme" / "Theme.qml"
OUT_QMLDIR = UI / "qml" / "Theme" / "qmldir"
OUT_PY = UI / "theme_tokens.py"
# Theme.qml's icon(name) resolves against the singleton's own folder: ui/qml/Theme/ -> ui/assets/icons/
ICON_DIR = "../../assets/icons/"
HEADER = "GENERATED by scripts/theme/gen_theme.py from scripts/theme/tokens.json — do not edit by hand"


# ---------------------------------------------------------------------------------------------------- token tree
class Token:
    def __init__(self, path: str, type_: str, value: Any, ext: dict, description: str = ""):
        self.path = path
        self.type = type_
        self.raw = value
        self.ext = ext
        self.description = description
        self.value: Any = None  # resolved

    @property
    def name(self) -> str:
        """The generated property name: an explicit override, else camelCase of the path minus the theme prefix and
        any 'base' segment (theme.dark.surface.card -> surfaceCard, theme.dark.accent.base -> accent)."""
        if "name" in self.ext:
            return self.ext["name"]
        parts = self.path.split(".")
        if parts[0] == "theme":
            parts = parts[2:]
        parts = [p for p in parts if p != "base"]
        return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def load_tokens(path: Path = TOKENS) -> dict[str, Token]:
    data = json.loads(path.read_text(encoding="utf-8"))
    out: dict[str, Token] = {}

    def walk(node: dict, prefix: list[str], inherited_type: str | None):
        t = node.get("$type", inherited_type)
        if "$value" in node:
            ext = (node.get("$extensions") or {}).get("roundtable", {})
            out[".".join(prefix)] = Token(".".join(prefix), t or "", node["$value"], ext, node.get("$description", ""))
            return
        for k, v in node.items():
            if k.startswith("$"):
                continue
            if isinstance(v, dict):
                walk(v, prefix + [k], t)

    walk(data, [], None)
    return out


_REF = re.compile(r"^\{([^}]+)\}$")


def _ref(value: str) -> str | None:
    m = _REF.match(value)
    return m.group(1) if m else None


def _resolve_color(tok: Token, tokens: dict[str, Token], seen: tuple = ()) -> Rgba:
    if tok.value is not None:
        return tok.value
    if tok.path in seen:
        raise ValueError(f"reference cycle at {tok.path}")
    v = tok.raw
    if isinstance(v, str):
        ref = _ref(v)
        base = _resolve_color(tokens[ref], tokens, seen + (tok.path,)) if ref else parse_hex(v)
    elif isinstance(v, dict):
        space = v.get("colorSpace", "srgb")
        comps = v.get("components")
        alpha = float(v.get("alpha", 1.0))
        if space == "oklch" and comps:
            r, g, b = oklch_to_srgb(*comps)
            base = (r, g, b, alpha)
        elif space == "srgb":
            if "hex" in v:
                r, g, b, _ = parse_hex(v["hex"])
            elif comps:
                r, g, b = comps[0], comps[1], comps[2]
            else:
                raise ValueError(f"{tok.path}: an srgb colour needs hex or components")
            base = (r, g, b, alpha)
        else:
            raise ValueError(f"{tok.path}: unsupported colorSpace {space}")
    else:
        raise ValueError(f"{tok.path}: bad colour value {v!r}")
    if "dL" in tok.ext:
        base = shift_lightness(base, float(tok.ext["dL"]))
    if "alpha" in tok.ext:
        base = (base[0], base[1], base[2], float(tok.ext["alpha"]))
    if "composite" in tok.ext:
        ref = _ref(tok.ext["composite"])
        bg = _resolve_color(tokens[ref], tokens, seen + (tok.path,)) if ref else parse_hex(tok.ext["composite"])
        base = composite(base, bg)
    tok.value = base
    return base


def _resolve_scalar(tok: Token, tokens: dict[str, Token]) -> Any:
    v = tok.raw
    ref = _ref(v) if isinstance(v, str) else None
    if ref:
        return _resolve_scalar(tokens[ref], tokens)
    if tok.type == "dimension":
        if isinstance(v, dict):
            return float(v["value"])
        return float(str(v).replace("px", ""))
    if tok.type == "duration":
        if isinstance(v, dict):
            return float(v["value"])
        return float(str(v).replace("ms", ""))
    return v


def resolve_all(tokens: dict[str, Token]) -> None:
    for tok in tokens.values():
        if tok.type == "color":
            _resolve_color(tok, tokens)
        else:
            tok.value = _resolve_scalar(tok, tokens)


VARIANTS: dict[str, str] = {"tarnished": "dark"}  # variant -> the theme it overrides (Tarnished = dark + olive)


def theme_roles(theme: str, tokens: dict[str, Token]) -> dict[str, Token]:
    """{propertyName: Token} for one theme; a variant is its base theme's roles with the variant's overrides on top."""
    base = {t.name: t for p, t in tokens.items() if p.startswith(f"theme.{VARIANTS.get(theme, theme)}.")}
    if theme in VARIANTS:
        over = {t.name: t for p, t in tokens.items() if p.startswith(f"theme.{theme}.")}
        unknown = set(over) - set(base)
        if unknown:
            raise SystemExit(
                f"tokens.json: theme.{theme} overrides roles {sorted(unknown)} that theme.{VARIANTS[theme]} lacks"
            )
        base = {**base, **over}
    return base


def theme_colors(theme: str, tokens: dict[str, Token] | None = None) -> dict[str, Rgba]:
    """{propertyName: rgba} for one theme ("dark" / "light" / a variant); what the contrast test consumes."""
    tokens = tokens or load_tokens()
    resolve_all(tokens)
    return {n: t.value for n, t in theme_roles(theme, tokens).items() if t.type == "color"}


def shared_tokens(tokens: dict[str, Token]) -> dict[str, Token]:
    return {p: t for p, t in tokens.items() if not p.startswith(("theme.", "primitive.", "ramp."))}


# ---------------------------------------------------------------------------------------------------- legacy names
# The Widgets launcher's theme.py keys -> role names (legacy_tokens() in the Python output), so theme.py reads the
# tokens while the Widgets views keep their keys; removed with the Widgets views (S9).
LEGACY_PY: dict[str, str] = {
    "text": "textPrimary",
    "surf": "surfaceCard",
    "border": "borderEdge",
    "line": "borderHairline",
    "hero_a": "surfaceCard",
    "hero_b": "surfacePage",
    "hero_border": "borderEdge",
    "accent": "accent",
    "accent_hover": "accentHover",
    "accent_press": "accentPress",
    "on_accent": "textOnAccent",
    "ghost": "fillGhost",
    "ghost_fg": "textPrimary",
    "ghost_bd": "borderHairline",
    "ghost_hv": "fillGhostHover",
    "selected": "accentSoft",
    "sidebar_bg": "surfaceBar",
    "sidebar_hover": "surfaceRow",
    "sidebar_selected": "accentSoft",
    "sidebar_selected_fg": "accent",
    "dialog_body": "surfaceCard",
    "dialog_border": "borderHairline",
    "dialog_footer": "surfaceInput",
    "accent_off_fg": "textDisabled",
    "accent_off_bd": "borderHairline",
    "pending": "accentSoft",
    "pending_border": "accentPress",
    "editor": "surfaceInput",
    "editor_fg": "textPrimary",
    "drop_surf": "surfaceBar",
    "focus": "accent",
    "focus_on_accent": "textOnAccent",
    "focus_inner": "textOnAccent",
    "success_fg": "statusSuccess",
    "success_bg": "statusSuccessBg",
    "warning_fg": "statusWarning",
    "warning_bg": "statusWarningBg",
    "danger": "statusDanger",
    "danger_bg": "statusDangerBg",
    "busy_bg": "accentSoft",
    "muted_bg": "statusInfoBg",
    "muted": "textSecondary",
    "shadow": "shadowColor",
    "hero_glow": "glowSoft",
}


# ---------------------------------------------------------------------------------------------------- QML output
def _qml_scalar(tok: Token) -> tuple[str, str]:
    """(qml type, literal) for a non-colour token."""
    v = tok.value
    if tok.type in ("dimension", "duration", "number"):
        if float(v).is_integer():
            return "int", str(int(v))
        return "real", repr(float(v))
    if tok.type == "fontWeight":
        return "int", str(int(v))
    if tok.type == "fontFamily":
        return "var", json.dumps(list(v))
    if isinstance(v, bool):
        return "bool", "true" if v else "false"
    if isinstance(v, (int, float)):
        return ("int", str(v)) if float(v).is_integer() else ("real", repr(float(v)))
    return "string", json.dumps(str(v))


def _group_of(path: str) -> str:
    parts = path.split(".")
    if parts[0] == "theme":
        return parts[2]
    return parts[0]


def render_qml(tokens: dict[str, Token]) -> str:
    dark = theme_roles("dark", tokens)
    light = theme_roles("light", tokens)
    missing = set(dark) ^ set(light)
    if missing:
        raise SystemExit(f"tokens.json: roles not defined in both themes: {sorted(missing)}")
    variants = {v: {t.name: t for p, t in tokens.items() if p.startswith(f"theme.{v}.")} for v in VARIANTS}
    for v in variants:
        theme_roles(v, tokens)  # validates the overrides

    def dark_expr(name: str, fmt) -> str:
        """The dark-side expression: the variant ternaries (only where a variant overrides the role) around dark."""
        expr = fmt(dark[name])
        for v, over in variants.items():
            if name in over and over[name].value != dark[name].value:
                expr = f'variant === "{v}" ? {fmt(over[name])} : {expr}'
        return expr

    lines: list[str] = []
    w = lines.append
    w("pragma Singleton")
    w("pragma ComponentBehavior: Bound")
    w("import QtQuick")
    w("")
    w(f"// {HEADER}")
    w("// Regenerate: uv run python scripts/theme/gen_theme.py")
    w("//")
    w(
        "// Roles by elevation and purpose (technical specification §8.10): surface.*, border.*, text.*, accent.*, status.*,"
    )
    w("// glow.*, shadow.*, fill.* (translucent fills over whatever is behind), plus spacing, radius, type, motion,")
    w(
        "// geometry and the atmosphere ceilings. `dark` switches the theme; every colour below follows it. `variant` picks a"
    )
    w('// dark variant ("tarnished", the olive one) for the roles it overrides; anything else is the plain dark value.')
    w("QtObject {")
    w("    id: theme")
    w("")
    w("    property bool dark: true")
    w(f'    property string variant: ""  // "" | {" | ".join(repr(v) for v in VARIANTS)}')
    w("")

    # themed colours, grouped
    groups_seen: list[str] = []
    for dt in dark.values():
        g = _group_of(dt.path)
        if g not in groups_seen:
            groups_seen.append(g)
    descriptions = {
        "surface": "surfaces, by elevation: chrome (menu bar) < bar (top bar + rail) < page (inset) < card < row (hover) < pressed",
        "border": "lines: hairline inside content (1.3-1.6:1), edge on the inset corner and the menu-bar seam, tag (12%)",
        "text": "type: primary, secondary 70%, tertiary 50%, disabled 35%, onAccent; icon = text at 80%",
        "accent": "the action colour; hover / press derived in OKLCH (dark +6 L / -10 L, light -6 L / -10 L)",
        "status": "status hues shared between themes (success 150, warning 75, danger 20, info = accent); .bg at 15%",
        "glow": "glow system: soft 12% large radius, ring 35% tight, bloom 16% hero radial",
        "shadow": "shadows are never neutral: warm black in dark, blue-black in light; rest y1 b3, move y4 b12, float y8 b24",
        "fill": "translucent fills (white in dark, black in light): hover 4%, input / ghost 6%, ghost hover 10%, identity 8%",
        "atmosphere": "atmosphere ceilings: grain, bloom, tint and vignette opacities, bloom colours",
        "title": "titles: page and dialog headings",
        "card": "cards: a translucent tint so the page atmosphere shows through",
        "gold": "the gilded family: Launch, primary buttons; outline, inner frame, fill wash, sheen",
        "smear": "glow-smear hovers: rows, rail, ghost buttons",
        "frame": "the double frame: the active save card",
        "stat": "the character sheet",
    }
    for g in groups_seen:
        w(f"    // ---- {g}: {descriptions.get(g, '')}".rstrip(": "))
        for name, dt in dark.items():
            if _group_of(dt.path) != g:
                continue
            lt = light[name]
            if dt.type == "color":
                de = dark_expr(name, lambda t: f'"{qt_hex(t.value)}"')
                w(
                    f'    readonly property color {name}: dark ? {"(" + de + ")" if "?" in de else de} : "{qt_hex(lt.value)}"'
                )
            else:
                tp, dv = _qml_scalar(dt)
                _, lv = _qml_scalar(lt)
                w(f"    readonly property {tp} {name}: dark ? {dv} : {lv}")
        w("")

    # shared tokens
    shared = shared_tokens(tokens)
    sgroups: list[str] = []
    for t in shared.values():
        g = _group_of(t.path)
        if g not in sgroups:
            sgroups.append(g)
    sdesc = {
        "spacing": "spacing scale 4 / 8 / 12 / 16 / 24 / 32; space(n) = n * 4 for the odd case",
        "radius": "corners: control 4, card 3, inset 16, tag 2, pill 3, overlay 6, launch 5; rows have no radius",
        "type": "type sizes (caption 12, body 13, row title 14, section 18, page 22) and weights 400 / 500 / 600",
        "font": "UI family list (first installed wins, resolved once at startup); head / serif are the bundled display faces",
        "grain": "grain opacity per Settings > Appearance > Grain; AppState.grainOpacity picks one",
        "motion": "durations in ms; Easing.OutCubic everywhere; nothing over 200 ms",
        "geometry": "the shell's geometry (rows, bars, rail, breakpoints, reading widths) and the divider insets",
        "ceiling": "atmosphere intensities are ceilings; the atmosphere layer reads these, nothing else does",
    }
    for g in sgroups:
        w(f"    // ---- {g}: {sdesc.get(g, '')}".rstrip(": "))
        for t in shared.values():
            if _group_of(t.path) != g:
                continue
            tp, lit = _qml_scalar(t)
            w(f"    readonly property {tp} {t.name}: {lit}")
        if g == "font":
            w("    readonly property string fontFamily: resolveFontFamily()")
        w("")

    w("")
    w("    function space(n) {")
    w("        return n * 4;")
    w("    }")
    w("")
    w(
        "    // bundled SVGs (ui/assets/icons, Fluent UI System Icons, MIT), tinted by IconImage; no qrc, so Design Studio works"
    )
    w("    function icon(name) {")
    w(f'        return Qt.resolvedUrl("{ICON_DIR}" + name + ".svg");')
    w("    }")
    w("")
    w("    function resolveFontFamily() {")
    w("        const have = Qt.fontFamilies();")
    w("        for (let i = 0; i < fontFamilies.length; i++) {")
    w("            if (have.indexOf(fontFamilies[i]) >= 0)")
    w("                return fontFamilies[i];")
    w("        }")
    w("        return fontFamilies[fontFamilies.length - 1];")
    w("    }")
    w("}")
    return "\n".join(lines) + "\n"


def render_qmldir() -> str:
    return "module Theme\nsingleton Theme 1.0 Theme.qml\n"


# ---------------------------------------------------------------------------------------------------- Python output
def render_py(tokens: dict[str, Token]) -> str:
    """The Python module, formatted by ruff (so `--check` and `ruff format --check` agree)."""
    return _ruff_format(_render_py(tokens))


def _render_py(tokens: dict[str, Token]) -> str:
    dark = theme_roles("dark", tokens)
    light = theme_roles("light", tokens)
    shared = shared_tokens(tokens)
    lines: list[str] = []
    w = lines.append
    w(f'"""{HEADER}.')
    w("")
    w("The theme's roles as plain data, the same ones as ui/qml/Theme/Theme.qml: DARK, LIGHT and TARNISHED map a role")
    w("name to a QColor-ready string (#RRGGBB, or #AARRGGBB when translucent) or a number; SPACING, RADIUS, TYPE,")
    w("MOTION, GEOMETRY, CEILING and GRAIN are shared by all themes. No Qt here, so anything can read it; ui/theme.py")
    w("turns it into colours and style sheets. legacy_tokens(theme) maps the roles onto the Widgets views' older keys")
    w('until those views are replaced."""')
    w("")
    w("from __future__ import annotations")
    w("")

    def table(name: str, src: dict[str, Token]):
        w(f"{name}: dict[str, str | float] = {{")
        for n, t in src.items():
            if t.type == "color":
                w(f'    "{n}": "{qt_hex(t.value)}",')
            else:
                w(f'    "{n}": {_py_lit(t)},')
        w("}")
        w("")

    table("DARK", dark)
    table("LIGHT", light)
    for v in VARIANTS:
        table(v.upper(), theme_roles(v, tokens))
    w('THEMES = {"dark": DARK, "light": LIGHT' + "".join(f', "{v}": {v.upper()}' for v in VARIANTS) + "}")
    w("")
    groups: dict[str, dict[str, Token]] = {}
    for t in shared.values():
        groups.setdefault(_group_of(t.path).upper(), {})[t.name] = t
    for g, toks in groups.items():
        if g == "FONT":
            fam = next(iter(toks.values()))
            w(f"FONT_FAMILIES = {json.dumps(list(fam.value))}")
            w("")
            rest = {n: t for n, t in toks.items() if t is not fam}
            if rest:
                w("FONT = {")
                for n, t in rest.items():
                    w(f'    "{n}": {_py_lit(t)},')
                w("}")
                w("")
            continue
        w(f"{g} = {{")
        for n, t in toks.items():
            w(f'    "{n}": {_py_lit(t)},')
        w("}")
        w("")
    w("# the Widgets views' keys -> role names")
    w("LEGACY = {")
    for old, new in LEGACY_PY.items():
        w(f'    "{old}": "{new}",')
    w("}")
    w("")
    w("")
    w("def legacy_tokens(theme: str) -> dict[str, str]:")
    w('    """The Widgets views\' keys (tokens_dark() / tokens_light() in ui/theme.py), filled from the roles."""')
    w("    roles = THEMES[theme]")
    w("    return {old: str(roles[new]) for old, new in LEGACY.items()}")
    w("")
    w("")
    w("def font_family(available: list[str] | None = None) -> str:")
    w('    """The first family of FONT_FAMILIES that is installed (pass QFontDatabase.families()), else the last."""')
    w("    if available is not None:")
    w("        for f in FONT_FAMILIES:")
    w("            if f in available:")
    w("                return f")
    w("    return FONT_FAMILIES[-1]")
    return "\n".join(lines) + "\n"


def _py_lit(t: Token) -> str:
    v = t.value
    if t.type == "fontFamily":
        return json.dumps(list(v))
    if isinstance(v, bool):
        return repr(v)
    if isinstance(v, (int, float)):
        return str(int(v)) if float(v).is_integer() else repr(float(v))
    return json.dumps(v)


def _ruff_format(source: str) -> str:
    """Run the project's ruff over the generated source (its settings come from pyproject.toml)."""
    done = subprocess.run(
        [sys.executable, "-m", "ruff", "format", "--stdin-filename", str(OUT_PY), "-"],
        input=source.encode("utf-8"),
        capture_output=True,
        cwd=ROOT,
        check=False,
    )
    if done.returncode != 0:
        raise SystemExit(f"gen_theme: ruff format failed: {done.stderr.decode('utf-8', 'replace').strip()}")
    return done.stdout.decode("utf-8").replace("\r\n", "\n")


# ---------------------------------------------------------------------------------------------------- main
def outputs() -> dict[Path, str]:
    tokens = load_tokens()
    resolve_all(tokens)
    return {OUT_QML: render_qml(tokens), OUT_QMLDIR: render_qmldir(), OUT_PY: render_py(tokens)}


def generate(check: bool = False) -> int:
    stale = []
    for path, text in outputs().items():
        current = path.read_bytes().decode("utf-8") if path.exists() else None
        if current != text:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(text.encode("utf-8"))
                print(f"wrote {path.relative_to(ROOT)}")
        elif not check:
            print(f"unchanged {path.relative_to(ROOT)}")
    if check:
        for p in stale:
            print(f"STALE {p.relative_to(ROOT)}: run uv run python scripts/theme/gen_theme.py")
        return 1 if stale else 0
    return 0


def dump() -> int:
    toks = load_tokens()
    resolve_all(toks)
    for theme in ("dark", "light", *VARIANTS):
        print(f"[{theme}]")
        for name, c in theme_colors(theme, toks).items():
            L, C, H = srgb_to_oklch(*c[:3])
            print(f"  {name:22s} {qt_hex(c):10s}  oklch({L:.2f} {C:.3f} {H:5.1f})  a={c[3]:.2f}")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the outputs are not current; write nothing")
    ap.add_argument("--dump", action="store_true", help="print every resolved colour role per theme")
    a = ap.parse_args()
    sys.exit(dump() if a.dump else generate(check=a.check))
