"""Seamless Co-op operations the window uses: finding a setup's ini, its password, scaling and every
setting, sharing them, and the words the settings form shows."""

from roundtable_souls.coop.ini import (
    LINE_RE,
    PW_RE,
    SAVE_KINDS,
    SECTION_RE,
    SECTION_TITLES,
    SETTING_COPY,
    VOLUME_STOPS,
    _read,
    choice_label,
    ersc_ini_for,
    label_of,
    nearest_volume_stop,
    read_settings_meta,
    setting_face,
    write_keys,
    write_password,
)
from roundtable_souls.coop.scaling import (
    CUSTOM,
    NIGHTREIGN_SCALING,
    SCALING_KEYS,
    SCALING_LABELS,
    SCALING_PRESETS,
    ScalingSpec,
)
from roundtable_souls.coop.share import (
    COMMENT_PREFIX,
    JSON_FORMAT,
    export_settings,
    export_text,
    indent_lines,
    load_settings_json,
    parse_settings_json,
    plan_import,
    read_all_settings,
    strip_json_comments,
    toggle_comment,
)

__all__ = [
    "LINE_RE",
    "PW_RE",
    "SAVE_KINDS",
    "SECTION_RE",
    "SECTION_TITLES",
    "SETTING_COPY",
    "VOLUME_STOPS",
    "_read",
    "choice_label",
    "ersc_ini_for",
    "label_of",
    "nearest_volume_stop",
    "read_settings_meta",
    "setting_face",
    "write_keys",
    "write_password",
    "CUSTOM",
    "NIGHTREIGN_SCALING",
    "SCALING_KEYS",
    "SCALING_LABELS",
    "SCALING_PRESETS",
    "ScalingSpec",
    "COMMENT_PREFIX",
    "JSON_FORMAT",
    "export_settings",
    "export_text",
    "indent_lines",
    "load_settings_json",
    "parse_settings_json",
    "plan_import",
    "read_all_settings",
    "strip_json_comments",
    "toggle_comment",
]
