pragma Singleton
pragma ComponentBehavior: Bound
import QtQuick

// GENERATED by scripts/theme/gen_theme.py from scripts/theme/tokens.json — do not edit by hand
// Regenerate: uv run python scripts/theme/gen_theme.py
//
// Roles by elevation and purpose (technical specification §8.10): surface.*, border.*, text.*, accent.*, status.*,
// glow.*, shadow.*, fill.* (translucent fills over whatever is behind), plus spacing, radius, type, motion,
// geometry and the atmosphere ceilings. `dark` switches the theme; every colour below follows it. `variant` picks a
// dark variant ("tarnished", the olive one) for the roles it overrides; anything else is the plain dark value.
QtObject {
    id: theme

    property bool dark: true
    property string variant: ""  // "" | 'tarnished'

    // ---- surface: surfaces, by elevation: chrome (menu bar) < bar (top bar + rail) < page (inset) < card < row (hover) < pressed
    readonly property color surfaceChrome: dark ? (variant === "tarnished" ? "#0A0C06" : "#0C0C0B") : "#E8F3FF"
    readonly property color surfaceBar: dark ? (variant === "tarnished" ? "#0D1003" : "#0F100D") : "#DDEDFF"
    readonly property color surfacePage: dark ? (variant === "tarnished" ? "#121607" : "#151513") : "#EEF6FF"
    readonly property color surfaceCard: dark ? (variant === "tarnished" ? "#181B0C" : "#1C1C19") : "#FFFFFF"
    readonly property color surfaceRow: dark ? (variant === "tarnished" ? "#181B0C" : "#1C1C19") : "#E2F0FF"
    readonly property color surfacePressed: dark ? (variant === "tarnished" ? "#1F2213" : "#232320") : "#D6E7F8"
    readonly property color surfaceInput: dark ? (variant === "tarnished" ? "#242717" : "#282824") : "#F0F0F0"
    readonly property color surfaceAcrylic: dark ? (variant === "tarnished" ? "#D6141708" : "#D615170F") : "#CCFFFFFF"

    // ---- border: lines: hairline inside content (1.3-1.6:1), edge on the inset corner and the menu-bar seam, tag (12%)
    readonly property color borderHairline: dark ? "#1FE8E2C8" : "#2620324E"
    readonly property color borderEdge: dark ? "#24E8E2C8" : "#2720324E"
    readonly property color borderTag: dark ? "#24E8E2C8" : "#2420324E"

    // ---- text: type: primary, secondary 70%, tertiary 50%, disabled 35%, onAccent; icon = text at 80%
    readonly property color textPrimary: dark ? "#E3D2B3" : "#20324E"
    readonly property color textSecondary: dark ? "#C2E3D2B3" : "#B820324E"
    readonly property color textTertiary: dark ? "#8FE3D2B3" : "#9420324E"
    readonly property color textDisabled: dark ? "#5CE3D2B3" : "#5920324E"
    readonly property color textOnAccent: dark ? "#160B02" : "#FFFFFF"
    readonly property color textIcon: dark ? "#CCE3D2B3" : "#CC20324E"

    // ---- accent: the action colour; hover / press derived in OKLCH (dark +6 L / -10 L, light -6 L / -10 L)
    readonly property color accent: dark ? "#F9C043" : "#245BC4"
    readonly property color accentHover: dark ? "#FFD35A" : "#1148B0"
    readonly property color accentPress: dark ? "#BD6707" : "#033CA3"
    readonly property color accentSoft: dark ? "#24F9C043" : "#1A245BC4"
    readonly property color accentGlow: dark ? "#66F9C043" : "#59245BC4"

    // ---- status: status hues shared between themes (success 150, warning 75, danger 20, info = accent); .bg at 15%
    readonly property color statusSuccess: dark ? "#A6C98F" : "#146D34"
    readonly property color statusSuccessBg: dark ? "#1FA6C98F" : "#26146D34"
    readonly property color statusWarning: dark ? "#F2B544" : "#7F5400"
    readonly property color statusWarningBg: dark ? "#1FF2B544" : "#267F5400"
    readonly property color statusDanger: dark ? "#E08A7A" : "#A8353E"
    readonly property color statusDangerBg: dark ? "#1FE08A7A" : "#26A8353E"
    readonly property color statusInfo: dark ? "#F9C043" : "#245BC4"
    readonly property color statusInfoBg: dark ? "#26F9C043" : "#26245BC4"
    readonly property color statusBadge: dark ? "#D13438" : "#D13438"

    // ---- glow: glow system: soft 12% large radius, ring 35% tight, bloom 16% hero radial
    readonly property color glowColor: dark ? "#F9C043" : "#63B5F5"
    readonly property color glowSoft: dark ? "#24F9C043" : "#4763B5F5"
    readonly property color glowRing: dark ? "#52F9C043" : "#7A63B5F5"
    readonly property color glowBloom: dark ? "#29F9C043" : "#2963B5F5"
    readonly property color glowRest: dark ? "#14F9C043" : "#2663B5F5"

    // ---- shadow: shadows are never neutral: warm black in dark, blue-black in light; rest y1 b3, move y4 b12, float y8 b24
    readonly property color shadowColor: dark ? "#80000000" : "#29294C7A"
    readonly property color shadowRest: dark ? "#40000000" : "#14294C7A"
    readonly property color shadowMove: dark ? "#66000000" : "#1F294C7A"

    // ---- fill: translucent fills (white in dark, black in light): hover 4%, input / ghost 6%, ghost hover 10%, identity 8%
    readonly property color fillHover: dark ? "#0BE8E2C8" : "#0A000000"
    readonly property color fillInput: dark ? "#0FE8E2C8" : "#0F000000"
    readonly property color fillGhost: dark ? "#00000000" : "#00000000"
    readonly property color fillGhostHover: dark ? "#16E8E2C8" : "#1A000000"
    readonly property color fillGhostPress: dark ? "#0BE8E2C8" : "#08000000"
    readonly property color fillIdentity: dark ? "#0FE8E2C8" : "#14000000"
    readonly property color fillScrim: dark ? "#73000000" : "#47294C7A"
    readonly property color fillDim: dark ? "#59000000" : "#29294C7A"

    // ---- atmosphere: atmosphere ceilings: grain, bloom, tint and vignette opacities, bloom colours
    readonly property color atmosphereBloomA: dark ? "#0DF9C043" : "#3363B5F5"
    readonly property color atmosphereBloomB: dark ? (variant === "tarnished" ? "#2E8FA05A" : "#1F969E70") : "#E6FFFFFF"
    readonly property color atmosphereVignette: dark ? "#57000000" : "#00000000"
    readonly property color atmosphereLuminousEdge: dark ? "#1FF9C043" : "#1F245BC4"

    // ---- title: titles: page and dialog headings
    readonly property color title: dark ? "#EAD7A4" : "#1A2F57"

    // ---- card: cards: a translucent tint so the page atmosphere shows through
    readonly property color cardFill: dark ? "#33000000" : "#B8FFFFFF"

    // ---- gold: the gilded family: Launch, primary buttons; outline, inner frame, fill wash, sheen
    readonly property color goldText: dark ? "#F3CF72" : "#1D4FB0"
    readonly property color goldLine: dark ? "#8CF0C45C" : "#80245BC4"
    readonly property color goldLineHover: dark ? "#F2F6CE6E" : "#E6245BC4"
    readonly property color goldInner: dark ? "#38F0C45C" : "#29245BC4"
    readonly property color goldFillTop: dark ? "#21F9C043" : "#14245BC4"
    readonly property color goldFillTopHover: dark ? "#38F9C043" : "#24245BC4"
    readonly property color goldFillBottom: dark ? "#0DF9C043" : "#08245BC4"
    readonly property color goldFillBottomHover: dark ? "#1AF9C043" : "#0F245BC4"
    readonly property color goldSheen: dark ? "#24FFE8AA" : "#99FFFFFF"

    // ---- smear: glow-smear hovers: rows, rail, ghost buttons
    readonly property color smearHover: dark ? "#16DED7C1" : "#13245BC4"
    readonly property color smearSelected: dark ? "#33F9C043" : "#4263B5F5"

    // ---- frame: the double frame: the active save card
    readonly property color frameBorder: dark ? "#80C9B478" : "#80245BC4"
    readonly property color frameInner: dark ? "#33C9B478" : "#33245BC4"

    // ---- stat: the character sheet
    readonly property color statBar: dark ? "#6BDED7C1" : "#5220324E"

    // ---- spacing: spacing scale 4 / 8 / 12 / 16 / 24 / 32; space(n) = n * 4 for the odd case
    readonly property int sp2: 2
    readonly property int sp4: 4
    readonly property int sp6: 6
    readonly property int sp8: 8
    readonly property int sp10: 10
    readonly property int sp12: 12
    readonly property int sp16: 16
    readonly property int sp20: 20
    readonly property int sp24: 24
    readonly property int sp32: 32
    readonly property int sp40: 40

    // ---- radius: corners: control 4, card 3, inset 16, tag 2, pill 3, overlay 6, launch 5; rows have no radius
    readonly property int radiusControl: 4
    readonly property int radiusCard: 3
    readonly property int radiusInset: 16
    readonly property int radiusTag: 2
    readonly property int radiusPill: 999
    readonly property int radiusOverlay: 6
    readonly property int radiusLaunch: 5

    // ---- type: type sizes (caption 12, body 13, row title 14, section 18, page 22) and weights 400 / 500 / 600
    readonly property int fontCaption: 12
    readonly property int fontBody: 13
    readonly property int fontRow: 14
    readonly property int fontSection: 18
    readonly property int fontPage: 22
    readonly property int fontTag: 11
    readonly property int weightRegular: 400
    readonly property int weightMedium: 500
    readonly property int weightSemibold: 600

    // ---- font: UI family list (first installed wins, resolved once at startup); head / serif are the bundled display faces
    readonly property var fontFamilies: ["Inter", "Segoe UI Variable Text", "Segoe UI Variable", "Segoe UI", "Inter", "Noto Sans", "sans-serif"]
    readonly property string fontHead: "Cormorant Garamond"
    readonly property string fontSerif: "EB Garamond"
    readonly property real headScale: 1.26
    readonly property string fontFamily: resolveFontFamily()

    // ---- motion: durations in ms; Easing.OutCubic everywhere; nothing over 200 ms
    readonly property int mFast: 90
    readonly property int mPress: 60
    readonly property int mToggle: 140
    readonly property int mPage: 120
    readonly property int mRail: 160
    readonly property int mDrag: 120
    readonly property int mToastIn: 160
    readonly property int mToastOut: 120
    readonly property int mTooltipDelay: 500
    readonly property int mToastHold: 4500

    // ---- geometry: the shell's geometry (rows, bars, rail, breakpoints, reading widths) and the divider insets
    readonly property int menuRowH: 30
    readonly property int barRowH: 54
    readonly property int titleRowH: 32
    readonly property int controlH: 32
    readonly property int rowH: 48
    readonly property int iconRow: 16
    readonly property int iconButton: 20
    readonly property int railW: 190
    readonly property int railCollapsedW: 48
    readonly property int compactBelow: 820
    readonly property int sideBySideFrom: 760
    readonly property int dividerInset: 56
    readonly property int dividerEndInset: 16
    readonly property int focusRingW: 2
    readonly property int focusRingGap: 2
    readonly property int contentMaxW: 1240
    readonly property int formMaxW: 980
    readonly property int glowHaloRest: 3
    readonly property int glowHaloHover: 6
    readonly property int controlSmallH: 28
    readonly property int controlLargeH: 36
    readonly property int gapInline: 8
    readonly property int gapStack: 12
    readonly property int gapSection: 24
    readonly property int padCard: 16
    readonly property int padDialog: 24
    readonly property int rowCompactH: 36
    readonly property int inputW: 240
    readonly property int inputShortW: 120
    readonly property int pickerW: 240
    readonly property int pickerGameW: 168
    readonly property int pickerProfileW: 224
    readonly property int buttonMinW: 88

    // ---- ceiling: atmosphere intensities are ceilings; the atmosphere layer reads these, nothing else does
    readonly property real ceilingBloom: 0.08
    readonly property int ceilingBlurPx: 24
    readonly property int ceilingBlurToastPx: 12
    readonly property real ceilingTintDark: 0.7
    readonly property real ceilingTintLight: 0.8
    readonly property real ceilingTintDragGhost: 0.5
    readonly property real ceilingVignette: 0.34
    readonly property int ceilingFrostBloomRadius: 600
    readonly property int ceilingGlowBudget: 3

    // ---- grain: grain opacity per Settings > Appearance > Grain; AppState.grainOpacity picks one
    readonly property real grainSubtleDark: 0.06
    readonly property int grainSubtleLight: 0
    readonly property real grainFilmDark: 0.14
    readonly property real grainFilmLight: 0.12


    function space(n) {
        return n * 4;
    }

    // bundled SVGs (ui/assets/icons, Fluent UI System Icons, MIT), tinted by IconImage; no qrc, so Design Studio works
    function icon(name) {
        return Qt.resolvedUrl("../../assets/icons/" + name + ".svg");
    }

    function resolveFontFamily() {
        const have = Qt.fontFamilies();
        for (let i = 0; i < fontFamilies.length; i++) {
            if (have.indexOf(fontFamilies[i]) >= 0)
                return fontFamilies[i];
        }
        return fontFamilies[fontFamilies.length - 1];
    }
}
